---
version: "3"

volumes:
  postgres_data:

services:
  app:
    build: .
    environment:
      - PYTHONUNBUFFERED
      - APP_ENVIRONMENT
      - APP_DEBUG
      - APP_HOST
      - APP_PORT
      - APP_TIMEZONE
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/alpas
      - DATABASE_NAME=alpas
    expose:
      - ${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./src:/opt/alpas-ai-solution/src
      - ./scripts:/opt/alpas-ai-solution/scripts
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:12.7
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alpas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - .env